name: epicwallet # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '4.0.5-beta+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: P2P electronic cash wallet # 79 char long summary
description: |
  EPIC is a novel software implementation of the original Bitcoin Standard,
  updated to the most recent technologies.

  The Epic GUI Wallet makes it simple to send and receive EPIC.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  epicwallet:
    # See 'snapcraft plugins'
    plugin: npm
    npm-node-version: 18.6.0
    source: .
